### ISSUE TITLE
Permissions Error Jupyter on Maneframe

### ISSUE THREAD

**Issue by eclarson** [justinledford/maneframe-jupyter-notebook#1]
Any body seen this error on mainframe before when trying to use the launch nb script (copied)?

I think this error has to do with the permissions for when actually launching jupyter... so an error in the way jupyter was updated on maneframe? Not sure. 

```
Launching jupyter notebook...
Traceback (most recent call last):
  File "/hpc/applications/anaconda/3/lib/python3.6/site-packages/traitlets/traitlets.py", line 528, in get
    value = obj._trait_values[self.name]
KeyError: 'runtime_dir'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/hpc/applications/anaconda/3/bin/jupyter-notebook", line 6, in <module>
    sys.exit(notebook.notebookapp.main())
  File "/hpc/applications/anaconda/3/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/hpc/applications/anaconda/3/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/hpc/applications/anaconda/3/lib/python3.6/site-packages/notebook/notebookapp.py", line 1362, in start
    super(NotebookApp, self).start()
  File "/hpc/applications/anaconda/3/lib/python3.6/site-packages/jupyter_core/application.py", line 256, in start
    self.subapp.start()
  File "/hpc/applications/anaconda/3/lib/python3.6/site-packages/notebook/notebookapp.py", line 365, in start
    for serverinfo in list_running_servers(self.runtime_dir):
  File "/hpc/applications/anaconda/3/lib/python3.6/site-packages/traitlets/traitlets.py", line 556, in __get__
    return self.get(obj, cls)
  File "/hpc/applications/anaconda/3/lib/python3.6/site-packages/traitlets/traitlets.py", line 535, in get
    value = self._validate(obj, dynamic_default())
  File "/hpc/applications/anaconda/3/lib/python3.6/site-packages/jupyter_core/application.py", line 99, in _runtime_dir_default
    ensure_dir_exists(rd, mode=0o700)
  File "/hpc/applications/anaconda/3/lib/python3.6/site-packages/ipython_genutils/path.py", line 167, in ensure_dir_exists
    os.makedirs(path, mode=mode)
  File "/hpc/applications/anaconda/3/lib/python3.6/os.py", line 210, in makedirs
    makedirs(head, mode, exist_ok)
  File "/hpc/applications/anaconda/3/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/run/user/506256' 
```

**Comment by justinledford** [comment]
Add `export XDG_RUNTIME_DIR=""` to your .bashrc on Maneframe2 for a quick fix, I will add this to the script though.
